getSignedUrl:
  handler: src/handlers/getSignedUrl.handler
  events:
    - http:
        path: /getSignedUrl
        method: POST
        cors: true
generateSignedUrl:
  handler: src/handlers/generateSignedUrl.handler
  events:
    - http:
        path: /generateSignedUrl
        method: POST
        cors: true
executePayload:
  handler: src/handlers/executePayload.handler
  events:
    - s3:
        bucket: ${self:custom.S3LargeFileUploadBucket.name}
        event: s3:ObjectCreated:*
